insert into DANCE_TYPE (id, name) values (1,'Salsa Cubana');
insert into DANCE_TYPE (id, name) values (2,'Salsa LA');
insert into DANCE_TYPE (id, name) values (3,'Salsa NY');
insert into DANCE_TYPE (id, name) values (4,'Bachata Social');
insert into DANCE_TYPE (id, name) values (5,'Bachata Sensual');
insert into DANCE_TYPE (id, name) values (6,'Bachata Dominicana');
insert into DANCE_TYPE (id, name) values (7,'Kizomba Social');
insert into DANCE_TYPE (id, name) values (8,'Kizomba Tradicional');
insert into DANCE_TYPE (id, name) values (9,'Kizomba Urbankizz');

insert into ARTICLE (id, title, date, pair, dance_type_id, youTube, thumb) values (1,'Salsa Cubana 1 Title', '2019-09-01', 'Chris&Aga', 1, 'https://www.youtube.com/embed/tgbNymZ7vqY', '1.jpg');
insert into ARTICLE (id, title, date, pair, dance_type_id, youTube, thumb) values (2,'Salsa Cubana 2 Title', '2019-09-01', 'Chris&Aga', 1, 'https://www.youtube.com/embed/gMp0SlkVU8w', '2.jpg');
insert into ARTICLE (id, title, date, pair, dance_type_id, youTube, thumb) values (3,'Salsa LA 1 Title', '2019-09-02', 'Chris&Aga', 2, 'https://www.youtube.com/embed/ZrqF7yD10Bo', '3.jpg');
insert into ARTICLE (id, title, date, pair, dance_type_id, youTube, thumb) values (4,'Salsa LA 2 Title', '2019-09-02', 'Chris&Iga', 2, 'https://www.youtube.com/embed/fZ9WiuJPnNA', '4.jpg');
insert into ARTICLE (id, title, date, pair, dance_type_id, youTube, thumb) values (5,'Salsa NY 1 Title', '2019-09-03', 'Chris&Iga', 3, 'https://www.youtube.com/embed/cUusX1Js6R0', '5.jpg');
insert into ARTICLE (id, title, date, pair, dance_type_id, youTube, thumb) values (6,'Salsa NY 2 Title', '2019-09-03', 'Chris&Iga', 3, 'https://www.youtube.com/embed/5BDVvB7Xx1w', '6.jpg');
insert into ARTICLE (id, title, date, pair, dance_type_id, youTube, thumb) values (7,'Salsa NY 3 Title', '2019-09-03', 'Chris&Iga', 3, 'https://www.youtube.com/embed/5BDVvB7Xx1w', '6.jpg');
insert into ARTICLE (id, title, date, pair, dance_type_id, youTube, thumb) values (8,'Salsa NY 4 Title', '2019-09-03', 'Chris&Iga', 3, 'https://www.youtube.com/embed/5BDVvB7Xx1w', '6.jpg');
insert into ARTICLE (id, title, date, pair, dance_type_id, youTube, thumb) values (9,'Salsa NY 5 Title', '2019-09-03', 'Chris&Iga', 3, 'https://www.youtube.com/embed/5BDVvB7Xx1w', '6.jpg');
insert into ARTICLE (id, title, date, pair, dance_type_id, youTube, thumb) values (10,'Salsa NY 6 Title', '2019-09-03', 'Chris&Iga', 3, 'https://www.youtube.com/embed/5BDVvB7Xx1w', '6.jpg');
insert into ARTICLE (id, title, date, pair, dance_type_id, youTube, thumb) values (11,'Salsa NY 7 Title', '2019-09-03', 'Chris&Iga', 3, 'https://www.youtube.com/embed/5BDVvB7Xx1w', '6.jpg');
insert into ARTICLE (id, title, date, pair, dance_type_id, youTube, thumb) values (12,'Salsa NY 7 Title', '2019-09-03', 'Chris&Iga', 3, 'https://www.youtube.com/embed/5BDVvB7Xx1w', '6.jpg');
insert into ARTICLE (id, title, date, pair, dance_type_id, youTube, thumb) values (13,'Salsa NY 7 Title', '2019-09-03', 'Chris&Iga', 3, 'https://www.youtube.com/embed/5BDVvB7Xx1w', '6.jpg');